export const copy = {
    loading: "Loading local draft…", saved: "Saved locally", draft: "Local draft", unsaved: "Not saved",
    loadError: "Your saved draft could not be loaded. A fresh workspace is ready; export a backup before leaving.",
    storageError: "Browser storage is unavailable. Export your design system to keep a copy.",
    copied: "Copied to clipboard", clipboardError: "Clipboard unavailable. Use Download instead.",
    skip: "Skip to workspace", home: "bambiui home", name: "Design system name", beta: "BETA",
    import: "Import", importAria: "Import design system", importJson: "Import design system JSON",
    fileSize: "The file must be smaller than 100 KB.", replace: "Replace the current design system with this file?",
    imported: "Design system imported successfully. Both themes are ready.", importFailed: "Import failed", invalidJson: "Invalid JSON file.",
    export: "Export tokens", exportTitle: "Take your system with you.", closeExport: "Close export dialog",
    exportDescription: "Export both themes as CSS variables (including derived states), or JSON with theme sources and overrides. Component markup and styles are not included.",
    exportFormat: "Export format", exported: "Exported tokens", copy: "Copy", download: "Download",
    library: "Component library", yourSystem: "Your design system", feel: "Make it feel like you.", workspace: "Workspace", overview: "Overview",
    globalTokens: "Global tokens", components: "Components", search: "Search components", find: "Find a component…",
    customTitle: "Has custom tokens", custom: ", has custom tokens", noComponents: "No components found.",
    tip: "Small tokens. Big possibilities.", tipDetail: "Start with your foundations, then make every component your own.", builtWith: "Built with Base UI",
    overviewTitle: "Your design system", componentTitle: (name: string) => name,
    overviewIntro: "One place to shape your foundations and see them in action.", componentIntro: "Fine-tune the details. Every change is reflected in real time.", live: "Live preview",
    workspaceView: "Workspace view", design: "Design", develop: "Develop", responsive: "Responsive", width: "Preview width", desktop: "Desktop preview", mobile: "Mobile preview",
    theme: "Design theme", light: "Light", dark: "Dark",
    dismiss: "Dismiss notification", collection: "COMPONENT COLLECTION", explorer: (name: string) => `${name.toUpperCase()} EXPLORER`, interactive: "INTERACTIVE",
    jumpToTokens: "Edit tokens", backToPreview: "Back to preview", backToCode: "Back to code",
    editor: "Design token editor", inspector: "Token inspector", scope: "Token scope", component: "Component", editTokens: (mode: string) => `Edit ${mode} theme tokens`,
    foundations: "The foundations", componentTokens: (name: string) => `${name} tokens`, foundationsHint: "Shared across every component.",
    inheritComponent: "Values inherit from global tokens until you change them. Reset to reconnect.",
    colors: "Colors", shape: "Shape & spacing", resetGlobal: "Reset global tokens", resetComponent: "Reset component overrides", changes: "Changes apply instantly",
    confirmGlobal: (mode: string) => `Reset ${mode} global tokens? Component overrides and the other theme will be kept.`,
    confirmComponent: (mode: string, name: string) => `Reset all ${mode} ${name} overrides to global tokens?`,
    override: "Override", inherited: "Global", resetOverride: (name: string) => `Reset ${name.toLowerCase()} override`, resetTip: "Reset to global token", inheritedTip: "Inherited from global tokens",
    colorPicker: (name: string) => `${name} color picker`, slider: (name: string) => `${name} slider`, invalidColor: "Use a six-digit hex color.", invalidNumber: (min: number, max: number) => `Use a value from ${min} to ${max}.`,
    tokenLabels: {
      background: "Background", foreground: "Foreground", muted: "Muted", mutedForeground: "Muted foreground", border: "Border", primary: "Primary", onPrimary: "On primary", secondary: "Secondary", onSecondary: "On secondary", success: "Success", onSuccess: "On success", warning: "Warning", onWarning: "On warning", danger: "Danger", onDanger: "On danger", info: "Info", onInfo: "On info", radius: "Radius", paddingX: "Horizontal padding", paddingY: "Vertical padding", gap: "Gap", margin: "Margin", fontSize: "Font size", borderWidth: "Border width", controlHeightSm: "Control height sm", controlHeightMd: "Control height md", controlHeightLg: "Control height lg",
    },
    componentNames: { button: "Button", input: "Input", card: "Card", badge: "Badge", switch: "Switch", checkbox: "Checkbox", text: "Text" },
};
